### ISSUE TITLE
File Upload fails at 98 %

### ISSUE THREAD

**Issue by Kalyan001** [barissenkal/Node.js-LAN-File-Sharing#5]

**Comment by barissenkal** [comment]
Do you have an error log? What was the size of the file? Is it all files or only some?

**Comment by Kalyan001** [comment]
Hi,
While uploading any video file > 1gb, in the browser I see the % of upload
going till 98% and then failing with "upload failed error"

Regards,
Kalyan

**Comment by barissenkal** [comment]
There was a 200mb size limit due to [formidable](https://github.com/node-formidable/formidable)'s default config. Updated to 100gb (via 8eda615)
