### ISSUE TITLE
Upload in web browser

### ISSUE THREAD

**Issue by meav** [barissenkal/Node.js-LAN-File-Sharing#7]
Thank you because fix this issue: https://github.com/barissenkal/Node.js-LAN-File-Sharing/issues/6

But when I use last version, I have some questions:
- Can I upload single or multiple file without upload folder?
- When use browser in android, upload not work. I guess in android, I can't upload folder. I think you should have two buttons in browser: Upload files and Upload folder.
- I think you should set default folder not expand when view in browser.

Sorry for my bad english and thank you!

**Comment by meav** [comment]
Update: I can't drag and drop (file or folder) in windows.

**Comment by barissenkal** [comment]
I added configs for multiple file and folder upload (a15a627).

This is a temporary fix but these settings should ideally be configured by the page automatically based on the browser.
